[32mINFO    [0m integration.test_backups:test_backups.py:331 Deploying a new mysql cluster
[32mINFO    [0m juju.model:model.py:2069 Deploying local:jammy/mysql-1
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [executing] maintenance: Installing MySQL
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [executing] maintenance: Setting up cluster node
[33mWARNING [0m juju.model:model.py:1558 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: Primary
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: Primary
[32mINFO    [0m integration.test_backups:test_backups.py:351 Rotating all mysql credentials
[32mINFO    [0m integration.test_backups:test_backups.py:371 Syncing credentials for aws
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [executing] active: Primary
  s3-integrator/0 [executing] active: 
[32mINFO    [0m integration.test_backups:test_backups.py:387 Restoring backup with id 2024-03-23T01:33:22Z
[32mINFO    [0m integration.test_backups:test_backups.py:394 Ensuring that the pre-backup inserted value exists in database, while post-backup inserted value does not
[32mINFO    [0m integration.test_backups:test_backups.py:407 Inserting value after restore from aws
[32mINFO    [0m integration.helpers:helpers.py:474 Retrieving primary unit
[32mINFO    [0m integration.test_backups:test_backups.py:415 Ensuring that pre-backup and post-restore values exist in the database
[32mINFO    [0m integration.test_backups:test_backups.py:371 Syncing credentials for gcp
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [executing] active: 
  s3-integrator/0 [executing] active: 
[32mINFO    [0m integration.test_backups:test_backups.py:387 Restoring backup with id 2024-03-23T01:33:53Z
[32mINFO    [0m integration.test_backups:test_backups.py:394 Ensuring that the pre-backup inserted value exists in database, while post-backup inserted value does not
[32mINFO    [0m integration.test_backups:test_backups.py:407 Inserting value after restore from gcp
[32mINFO    [0m integration.helpers:helpers.py:474 Retrieving primary unit
[32mINFO    [0m integration.test_backups:test_backups.py:415 Ensuring that pre-backup and post-restore values exist in the database
[32mINFO    [0m integration.test_backups:test_backups.py:371 Syncing credentials for ceph
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: 
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.test_backups:test_backups.py:387 Restoring backup with id 2024-03-23T01:34:22Z
[32mINFO    [0m integration.test_backups:test_backups.py:394 Ensuring that the pre-backup inserted value exists in database, while post-backup inserted value does not
[32mINFO    [0m integration.test_backups:test_backups.py:407 Inserting value after restore from ceph
[32mINFO    [0m integration.helpers:helpers.py:474 Retrieving primary unit
[32mINFO    [0m integration.test_backups:test_backups.py:415 Ensuring that pre-backup and post-restore values exist in the database
[32mINFO    [0m integration.test_backups:test_backups.py:425 Scaling mysql application to 3 units
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: 
  another-mysql/1 [allocating] waiting: waiting for machine
  another-mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/1 [allocating] waiting: waiting for machine
  another-mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/1 [allocating] waiting: agent initialising
  another-mysql/2 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/1 [executing] maintenance: Installing MySQL
  another-mysql/2 [executing] maintenance: Installing MySQL
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: Primary
  another-mysql/1 [executing] maintenance: Setting up cluster node
  another-mysql/2 [executing] maintenance: Setting up cluster node
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: Primary
  another-mysql/1 [executing] maintenance: joining the cluster
  another-mysql/2 [executing] active: 
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  another-mysql/0 [idle] active: Primary
  another-mysql/1 [idle] active: 
  another-mysql/2 [idle] active: 
[32mINFO    [0m integration.test_backups:test_backups.py:428 Ensuring inserted values before backup and after restore exist on all units
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.7    unsupported  01:50:22Z

App            Version          Status  Scale  Charm          Channel        Rev  Exposed  Message
another-mysql  8.0.36-0ubun...  active      3  mysql                           1  no       
mysql                           active      0  mysql                           0  no       
s3-integrator                   active      1  s3-integrator  latest/stable   13  no       

Unit              Workload  Agent  Machine  Public address  Ports           Message
another-mysql/0*  active    idle   6        10.5.149.113    3306,33060/tcp  Primary
another-mysql/1   active    idle   7        10.5.149.196    3306,33060/tcp  
another-mysql/2   active    idle   8        10.5.149.51     3306,33060/tcp  
s3-integrator/0*  active    idle   3        10.5.149.17                     

Machine  State    Address       Inst id        Base          AZ  Message
3        started  10.5.149.17   juju-3e8167-3  ubuntu@22.04      Running
6        started  10.5.149.113  juju-3e8167-6  ubuntu@22.04      Running
7        started  10.5.149.196  juju-3e8167-7  ubuntu@22.04      Running
8        started  10.5.149.51   juju-3e8167-8  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

machine-2: 01:29:05 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:29:05 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:29:05 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:29:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:29:06 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:29:06 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:29:06 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:29:06 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:29:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:29:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:29:07 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-mysql-1: 01:29:07 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:32:16 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:32:16 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:32:16 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 01:32:16 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:34:56 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
machine-2: 01:35:05 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
machine-5: 01:38:53 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:38:53 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:38:53 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-mysql-4: 01:38:53 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:38:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:38:55 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-4: 01:38:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-3: 01:38:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-4: 01:41:06 ERROR unit.mysql/4.juju-log Failed to get cluster status for test_cluster
unit-mysql-3: 01:41:06 ERROR unit.mysql/3.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-3/charm/src/mysql_vm_helpers.py", line 678, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmp6tdr9trw']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-3/charm/lib/charms/mysql/v0/mysql.py", line 1722, in get_cluster_primary_address
    output = self._run_mysqlsh_script("\n".join(get_cluster_primary_commands))
  File "/var/lib/juju/agents/unit-mysql-3/charm/src/mysql_vm_helpers.py", line 682, in _run_mysqlsh_script
    raise MySQLClientError(e.stderr)
charms.mysql.v0.mysql.MySQLClientError: b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nmysqlsh.Error: Shell Error (51104): Shell.connect_to_primary: Metadata for instance ecedc1c7-e8b5-11ee-bd3d-00163ebb4b1b not found\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-3/charm/./src/charm.py", line 778, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-3/charm/./src/charm.py", line 361, in _on_database_storage_detaching
    self._mysql.remove_instance(self.unit_label)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-3/charm/venv/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-3/charm/lib/charms/mysql/v0/mysql.py", line 1541, in remove_instance
    primary_address = self.get_cluster_primary_address()
  File "/var/lib/juju/agents/unit-mysql-3/charm/lib/charms/mysql/v0/mysql.py", line 1725, in get_cluster_primary_address
    raise MySQLGetClusterPrimaryAddressError(e.message)
charms.mysql.v0.mysql.MySQLGetClusterPrimaryAddressError: b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nmysqlsh.Error: Shell Error (51104): Shell.connect_to_primary: Metadata for instance ecedc1c7-e8b5-11ee-bd3d-00163ebb4b1b not found\n'
unit-mysql-4: 01:41:06 ERROR unit.mysql/4.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-4/charm/src/mysql_vm_helpers.py", line 678, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmpd0q7n0p1']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-4/charm/lib/charms/mysql/v0/mysql.py", line 1722, in get_cluster_primary_address
    output = self._run_mysqlsh_script("\n".join(get_cluster_primary_commands))
  File "/var/lib/juju/agents/unit-mysql-4/charm/src/mysql_vm_helpers.py", line 682, in _run_mysqlsh_script
    raise MySQLClientError(e.stderr)
charms.mysql.v0.mysql.MySQLClientError: b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nmysqlsh.Error: Shell Error (51104): Shell.connect_to_primary: Metadata for instance ecedc1c7-e8b5-11ee-bd3d-00163ebb4b1b not found\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-4/charm/./src/charm.py", line 778, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-4/charm/./src/charm.py", line 361, in _on_database_storage_detaching
    self._mysql.remove_instance(self.unit_label)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-4/charm/venv/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-4/charm/lib/charms/mysql/v0/mysql.py", line 1541, in remove_instance
    primary_address = self.get_cluster_primary_address()
  File "/var/lib/juju/agents/unit-mysql-4/charm/lib/charms/mysql/v0/mysql.py", line 1725, in get_cluster_primary_address
    raise MySQLGetClusterPrimaryAddressError(e.message)
charms.mysql.v0.mysql.MySQLGetClusterPrimaryAddressError: b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nmysqlsh.Error: Shell Error (51104): Shell.connect_to_primary: Metadata for instance ecedc1c7-e8b5-11ee-bd3d-00163ebb4b1b not found\n'
unit-mysql-3: 01:41:06 ERROR juju.worker.uniter.operation hook "database-storage-detaching" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-4: 01:41:06 ERROR juju.worker.uniter.operation hook "database-storage-detaching" (via hook dispatching script: dispatch) failed: exit status 1
machine-6: 01:42:37 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:42:37 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-6: 01:42:37 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-another-mysql-0: 01:42:37 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-8: 01:47:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-8: 01:47:55 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-8: 01:47:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-another-mysql-2: 01:47:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-7: 01:47:56 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 01:47:56 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 01:47:57 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-another-mysql-1: 01:47:57 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...
[32mINFO    [0m integration.test_backups:test_backups.py:102 Cleaning backups from cloud buckets