[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:78 Rebooting mysql/0
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:78 Rebooting mysql/1
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:78 Rebooting mysql/2
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:80 Sleep to allow juju status change
[32mINFO    [0m integration.test_vm_reboot:test_vm_reboot.py:82 Waiting for the application to become idle
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] active: 
  mysql/1 [executing] active: 
  mysql/2 [idle] active: Primary
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] maintenance: Unable to query cluster primary
  mysql/1 [idle] maintenance: offline
  mysql/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] maintenance: offline
  mysql/1 [idle] maintenance: offline
  mysql/2 [idle] maintenance: offline
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: Primary
  mysql/1 [executing] active: 
  mysql/2 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.8    unsupported  02:34:20Z

App    Version          Status  Scale  Charm  Channel  Rev  Exposed  Message
mysql  8.0.42-0ubun...  active      3  mysql             0  no       

Unit      Workload  Agent  Machine  Public address  Ports           Message
mysql/0*  active    idle   0        10.220.208.43   3306,33060/tcp  Primary
mysql/1   active    idle   1        10.220.208.220  3306,33060/tcp  
mysql/2   active    idle   2        10.220.208.2    3306,33060/tcp  

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.220.208.43   juju-37a1a8-0  ubuntu@22.04      Running
1        started  10.220.208.220  juju-37a1a8-1  ubuntu@22.04      Running
2        started  10.220.208.2    juju-37a1a8-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 02:26:00 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 02:26:00 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 02:26:00 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:27:31 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 02:27:31 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 02:27:31 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 02:27:33 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 02:27:33 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 02:27:33 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-0: 02:29:57 ERROR unit.mysql/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 795, in _run_mysqlsh_script
    output = subprocess.check_output(  # noqa: S603
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-37a1a8-2.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\ncluster.rejoin_instance('mysql-0')"]' returned non-zero exit status 1.
unit-mysql-0: 02:29:57 ERROR unit.mysql/0.juju-log Failed to rejoin instance mysql-0 to cluster test_cluster
unit-mysql-1: 02:32:36 ERROR unit.mysql/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 795, in _run_mysqlsh_script
    output = subprocess.check_output(  # noqa: S603
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@10.220.208.2:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\nshell.connect_to_primary()\nprimary_address = shell.parse_uri(session.uri)['host']\nprint(f'<PRIMARY_ADDRESS>{primary_address}</PRIMARY_ADDRESS>')"]' returned non-zero exit status 1.

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...