[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model concierge-lxd:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.high_availability.conftest:conftest.py:48 Deploying mysql and scaling to 3 units
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-0
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [executing] maintenance: Installing MySQL
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [executing] waiting: Waiting to start MySQL
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [executing] maintenance: Setting up cluster node
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] maintenance: Installing MySQL
  mysql/2 [executing] waiting: agent initialising
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] maintenance: Setting up cluster node
  mysql/1 [executing] active: Primary
  mysql/2 [executing] waiting: Waiting to start MySQL
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [executing] active: 
  mysql/1 [executing] active: Primary
  mysql/2 [executing] waiting: waiting to get cluster primary from peers
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: Primary
  mysql/2 [idle] active: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:51 Deploying mysql-test-app
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-73
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:54 Relating mysql with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql/0 [idle] active: 
  mysql/1 [idle] active: Primary
  mysql/2 [idle] active: 
  mysql-test-app/0 [idle] waiting: 
[32mINFO    [0m integration.high_availability.conftest:conftest.py:29 Clearing continuous writes
[32mINFO    [0m integration.high_availability.conftest:conftest.py:32 Starting continuous writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:342 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=512 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=517 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=523 on unit mysql/2
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:88 Ensure 3 units are online
[32mINFO    [0m integration.high_availability.test_self_healing_process_killed:test_self_healing_process_killed.py:51 Killing process id 5333
[32mINFO    [0m integration.high_availability.test_self_healing_process_killed:test_self_healing_process_killed.py:56 New process id is 11126
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:342 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1147 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1147 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1895 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1903 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:367 max_written_value=1910 on unit mysql/2
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.helpers:helpers.py:482 Retrieving primary unit
[32mINFO    [0m integration.high_availability.conftest:conftest.py:37 Clearing continuous writes
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.4    unsupported  01:39:52Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.41-0ubun...  active      3  mysql                          0  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   73  no       

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   3        10.29.170.211                   
mysql/0            active    idle   0        10.29.170.19    3306,33060/tcp  Primary
mysql/1*           active    idle   1        10.29.170.230   3306,33060/tcp  
mysql/2            active    idle   2        10.29.170.232   3306,33060/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.29.170.19   juju-3a49e2-0  ubuntu@22.04      Running
1        started  10.29.170.230  juju-3a49e2-1  ubuntu@22.04      Running
2        started  10.29.170.232  juju-3a49e2-2  ubuntu@22.04      Running
3        started  10.29.170.211  juju-3a49e2-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-1: 01:33:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:33:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:33:07 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:34:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:34:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:34:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:34:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:34:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:34:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:37:35 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:37:35 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:37:35 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-0: 01:38:45 ERROR unit.mysql/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 779, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-3a49e2-0.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\nprint(cluster.status({'extended': False}))"]' returned non-zero exit status 1.
unit-mysql-0: 01:38:45 ERROR unit.mysql/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-0: 01:38:52 ERROR unit.mysql/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 779, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-3a49e2-0.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\nprint(cluster.status({'extended': False}))"]' returned non-zero exit status 1.
unit-mysql-0: 01:38:52 ERROR unit.mysql/0.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:38:56 ERROR unit.mysql/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 779, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-3a49e2-1.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\nshell.connect_to_primary()\nprimary_address = shell.parse_uri(session.uri)['host']\nprint(f'<PRIMARY_ADDRESS>{primary_address}</PRIMARY_ADDRESS>')"]' returned non-zero exit status 1.
unit-mysql-1: 01:38:57 ERROR unit.mysql/1.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 779, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-3a49e2-1.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\nprint(cluster.status({'extended': False}))"]' returned non-zero exit status 1.
unit-mysql-1: 01:38:57 ERROR unit.mysql/1.juju-log Failed to get cluster status for test_cluster
unit-mysql-1: 01:38:57 ERROR unit.mysql/1.juju-log Failed to get cluster members
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/relations/mysql_provider.py", line 161, in _update_endpoints
    rw_endpoints, ro_endpoints, _ = self.charm._mysql.get_cluster_endpoints()
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 2152, in get_cluster_endpoints
    raise MySQLGetClusterEndpointsError("Failed to get endpoints from cluster status")
charms.mysql.v0.mysql.MySQLGetClusterEndpointsError: Failed to get endpoints from cluster status
unit-mysql-0: 01:39:01 ERROR unit.mysql/0.juju-log Failed to execute mysql-shell command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 779, in _run_mysqlsh_script
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri=serverconfig@juju-3a49e2-0.lxd:33062', '--python', '-c', "shell.options.set('useWizards', False)\nprint('###')\ncluster = dba.get_cluster('test_cluster')\nprint(cluster.status({'extended': False}))"]' returned non-zero exit status 1.
unit-mysql-0: 01:39:01 ERROR unit.mysql/0.juju-log Failed to get cluster status for test_cluster

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...