{"uid":"875c070a813ce1d9","name":"test_network_cut","fullName":"tests.integration.high_availability.test_self_healing#test_network_cut","historyId":"bb2aa2dc0f3a078ccd9996c1af51d19e","time":{"start":1738114586177,"stop":1738114959071,"duration":372894},"description":"Completely cut and restore network.","descriptionHtml":"<p>Completely cut and restore network.</p>\n","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7f56e42f8dd0 state=finished raised Exception>]","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/tests/integration/helpers.py\", line 434, in wait_network_restore\n    raise Exception\nException\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n                                ^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/tests/integration/high_availability/test_self_healing.py\", line 192, in test_network_cut\n    await wait_network_restore(ops_test, primary_unit.name)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 326, in iter\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x7f56e42f8dd0 state=finished raised Exception>]","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1738114084041,"stop":1738114084041,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1738114084041,"stop":1738114084041,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1738114084041,"stop":1738114084190,"duration":149},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"highly_available_cluster","time":{"start":1738114084190,"stop":1738114584120,"duration":499930},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1738114084190,"stop":1738114084190,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"continuous_writes","time":{"start":1738114584120,"stop":1738114586176,"duration":2056},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Completely cut and restore network.","status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7f56e42f8dd0 state=finished raised Exception>]","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/_asyncio.py\", line 50, in __call__\n    result = await fn(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/tests/integration/helpers.py\", line 434, in wait_network_restore\n    raise Exception\nException\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n                                ^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/tests/integration/high_availability/test_self_healing.py\", line 192, in test_network_cut\n    await wait_network_restore(ops_test, primary_unit.name)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/_asyncio.py\", line 88, in async_wrapped\n    return await fn(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/_asyncio.py\", line 47, in __call__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 326, in iter\n    raise retry_exc from fut.exception()\ntenacity.RetryError: RetryError[<Future at 0x7f56e42f8dd0 state=finished raised Exception>]","steps":[],"attachments":[{"uid":"823218b06e6eae82","name":"log","source":"823218b06e6eae82.txt","type":"text/plain","size":15370}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"continuous_writes::finalizer","time":{"start":1738114959124,"stop":1738114960156,"duration":1032},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"highly_available_cluster::finalizer","time":{"start":1738114960157,"stop":1738114960157,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1738114960157,"stop":1738114960157,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1738114960157,"stop":1738114960424,"duration":267},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1738114960424,"stop":1738114960425,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1738114960425,"stop":1738114960425,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1738114960425,"stop":1738114960425,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(3)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.high_availability"},{"name":"suite","value":"test_self_healing"},{"name":"host","value":"fv-az1371-570"},{"name":"thread","value":"10639-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.high_availability.test_self_healing"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"2873130a86d88eb2","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":9,"skipped":4,"passed":217,"unknown":7,"total":237},"items":[{"uid":"2a300f3fb1d69942","reportUrl":"../3436//#testresult/2a300f3fb1d69942","status":"passed","time":{"start":1738028163604,"stop":1738028543802,"duration":380198}},{"uid":"10887e5f985e0184","reportUrl":"../3433//#testresult/10887e5f985e0184","status":"passed","time":{"start":1737941761953,"stop":1737942172911,"duration":410958}},{"uid":"95e21759f3b0c0cd","reportUrl":"../3431//#testresult/95e21759f3b0c0cd","status":"passed","time":{"start":1737855391294,"stop":1737855809062,"duration":417768}},{"uid":"446a0e39e8290f8e","reportUrl":"../3429//#testresult/446a0e39e8290f8e","status":"passed","time":{"start":1737769046601,"stop":1737769410257,"duration":363656}},{"uid":"a8efc0dde26c9ad3","reportUrl":"../3418//#testresult/a8efc0dde26c9ad3","status":"broken","statusDetails":"tenacity.RetryError: RetryError[<Future at 0x7f006bbef890 state=finished raised Exception>]","time":{"start":1737682603347,"stop":1737682971795,"duration":368448}},{"uid":"cc39e72ebb2112f7","reportUrl":"../3412//#testresult/cc39e72ebb2112f7","status":"passed","time":{"start":1737596126699,"stop":1737596548967,"duration":422268}},{"uid":"dc985e3f025dad4c","reportUrl":"../3404//#testresult/dc985e3f025dad4c","status":"passed","time":{"start":1737509786259,"stop":1737510200672,"duration":414413}},{"uid":"e99be3beb0981666","reportUrl":"../3395//#testresult/e99be3beb0981666","status":"passed","time":{"start":1737423404615,"stop":1737423828742,"duration":424127}},{"uid":"7829b33b7a0960f4","reportUrl":"../3388//#testresult/7829b33b7a0960f4","status":"passed","time":{"start":1737336996819,"stop":1737337415561,"duration":418742}},{"uid":"20daa4df098d7ebf","reportUrl":"../3387//#testresult/20daa4df098d7ebf","status":"passed","time":{"start":1737250560507,"stop":1737250976271,"duration":415764}},{"uid":"7ea6302cd536bd92","reportUrl":"../3386//#testresult/7ea6302cd536bd92","status":"passed","time":{"start":1737164159155,"stop":1737164571233,"duration":412078}},{"uid":"126a38c8901ff0c","reportUrl":"../3379//#testresult/126a38c8901ff0c","status":"passed","time":{"start":1737077823990,"stop":1737078235038,"duration":411048}},{"uid":"49d3677b5548707a","reportUrl":"../3375//#testresult/49d3677b5548707a","status":"passed","time":{"start":1736991505975,"stop":1736991893651,"duration":387676}},{"uid":"42df715bb15cf02d","reportUrl":"../3370//#testresult/42df715bb15cf02d","status":"passed","time":{"start":1736905016282,"stop":1736905444148,"duration":427866}},{"uid":"7f78418c675b968e","reportUrl":"../3361//#testresult/7f78418c675b968e","status":"passed","time":{"start":1736818646471,"stop":1736819043811,"duration":397340}},{"uid":"1389bac307e1d904","reportUrl":"../3355//#testresult/1389bac307e1d904","status":"passed","time":{"start":1736732249012,"stop":1736732661218,"duration":412206}},{"uid":"c93d3be921e0d197","reportUrl":"../3354//#testresult/c93d3be921e0d197","status":"passed","time":{"start":1736645853642,"stop":1736646283322,"duration":429680}},{"uid":"55ef6ca3b4475330","reportUrl":"../3352//#testresult/55ef6ca3b4475330","status":"passed","time":{"start":1736559419707,"stop":1736559830624,"duration":410917}},{"uid":"5fb891db840398e8","reportUrl":"../3344//#testresult/5fb891db840398e8","status":"passed","time":{"start":1736473047623,"stop":1736473469566,"duration":421943}},{"uid":"58df2633ac48fd0d","reportUrl":"../3314//#testresult/58df2633ac48fd0d","status":"passed","time":{"start":1735868269662,"stop":1735868680033,"duration":410371}}]},"tags":["group(3)","asyncio","abort_on_fail"]},"source":"875c070a813ce1d9.json","parameterValues":[]}