{"uid":"a43b8720a154b270","name":"test_keystone_bundle_db_router","fullName":"tests.integration.relations.test_db_router#test_keystone_bundle_db_router","historyId":"ad21fbafc2837b04b8c6ab83bc122f6f","time":{"start":1722649299950,"stop":1722652004915,"duration":2704965},"description":"Deploy the keystone bundle to test the 'db-router' relation.\n\n    Args:\n        ops_test: The ops test framework\n    ","descriptionHtml":"<p>Deploy the keystone bundle to test the 'db-router' relation.</p>\n<pre><code>Args:\n    ops_test: The ops test framework\n</code></pre>\n","status":"broken","statusMessage":"asyncio.exceptions.TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 130, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 605, in sleep\n    return await future\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mysql-operator/mysql-operator/tests/integration/relations/test_db_router.py\", line 148, in test_keystone_bundle_db_router\n    await asyncio.gather(\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 1040, in block_until\n    await utils.block_until(done,\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 131, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1722649299793,"stop":1722649299793,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1722649299794,"stop":1722649299949,"duration":155},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1722649299794,"stop":1722649299794,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1722649299949,"stop":1722649299950,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"description":"Deploy the keystone bundle to test the 'db-router' relation.\n\n    Args:\n        ops_test: The ops test framework\n    ","status":"broken","statusMessage":"asyncio.exceptions.TimeoutError","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 130, in _block\n    await jasyncio.sleep(wait_period)\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 605, in sleep\n    return await future\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 433, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 112, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 155, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 108, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/mysql-operator/mysql-operator/tests/integration/relations/test_db_router.py\", line 148, in test_keystone_bundle_db_router\n    await asyncio.gather(\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 1040, in block_until\n    await utils.block_until(done,\n  File \"/home/runner/work/mysql-operator/mysql-operator/.tox/integration/lib/python3.10/site-packages/juju/utils.py\", line 131, in block_until\n    await jasyncio.shield(jasyncio.wait_for(_block(), timeout))\n  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError","steps":[],"attachments":[{"uid":"cc0ef1eafc1bf4f1","name":"log","source":"cc0ef1eafc1bf4f1.txt","type":"text/plain","size":17494}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"ops_test::finalizer","time":{"start":1722652004919,"stop":1722652020381,"duration":15462},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1722652004919,"stop":1722652004919,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1722652020382,"stop":1722652020382,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1722652020382,"stop":1722652020382,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1722652020382,"stop":1722652020382,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.relations"},{"name":"suite","value":"test_db_router"},{"name":"host","value":"fv-az891-146"},{"name":"thread","value":"8001-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.relations.test_db_router"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"2e454411b2b6090a","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":67,"unknown":1,"total":72},"items":[{"uid":"d9d3ec2bda09b097","reportUrl":"../2841//#testresult/d9d3ec2bda09b097","status":"broken","statusDetails":"asyncio.exceptions.TimeoutError","time":{"start":1722562780947,"stop":1722565486867,"duration":2705920}},{"uid":"63a8d73fcf4a9d6b","reportUrl":"../2839//#testresult/63a8d73fcf4a9d6b","status":"passed","time":{"start":1722476253887,"stop":1722477793563,"duration":1539676}},{"uid":"f90f1b12d685db61","reportUrl":"../2836//#testresult/f90f1b12d685db61","status":"passed","time":{"start":1722389373518,"stop":1722390775830,"duration":1402312}},{"uid":"5cecae6cc9d8a624","reportUrl":"../2832//#testresult/5cecae6cc9d8a624","status":"passed","time":{"start":1722303354688,"stop":1722304703646,"duration":1348958}},{"uid":"cb741bdec51ee103","reportUrl":"../2827//#testresult/cb741bdec51ee103","status":"passed","time":{"start":1722217408387,"stop":1722218847400,"duration":1439013}},{"uid":"41fd8389fc64bd97","reportUrl":"../2824//#testresult/41fd8389fc64bd97","status":"passed","time":{"start":1722130507427,"stop":1722131891586,"duration":1384159}},{"uid":"e99700fefedbb1e0","reportUrl":"../2819//#testresult/e99700fefedbb1e0","status":"passed","time":{"start":1722043964346,"stop":1722045331023,"duration":1366677}},{"uid":"23308cf3e02d227f","reportUrl":"../2811//#testresult/23308cf3e02d227f","status":"passed","time":{"start":1721957880546,"stop":1721959257010,"duration":1376464}},{"uid":"5dbbda4cdce1548f","reportUrl":"../2807//#testresult/5dbbda4cdce1548f","status":"passed","time":{"start":1721871322485,"stop":1721872765543,"duration":1443058}},{"uid":"be7bb5aea59e8301","reportUrl":"../2802//#testresult/be7bb5aea59e8301","status":"passed","time":{"start":1721785710846,"stop":1721787116916,"duration":1406070}},{"uid":"c574fd07178784fe","reportUrl":"../2797//#testresult/c574fd07178784fe","status":"passed","time":{"start":1721698467099,"stop":1721700926680,"duration":2459581}},{"uid":"a3acdb8d23082023","reportUrl":"../2787//#testresult/a3acdb8d23082023","status":"passed","time":{"start":1721612067566,"stop":1721613938544,"duration":1870978}},{"uid":"de6bfb46a906104f","reportUrl":"../2786//#testresult/de6bfb46a906104f","status":"passed","time":{"start":1721525740473,"stop":1721527125795,"duration":1385322}},{"uid":"ba54609d95ac43db","reportUrl":"../2785//#testresult/ba54609d95ac43db","status":"unknown","time":{}},{"uid":"60b96235c56c5979","reportUrl":"../2776//#testresult/60b96235c56c5979","status":"passed","time":{"start":1721266768648,"stop":1721268536093,"duration":1767445}},{"uid":"52b59c23f61e0c15","reportUrl":"../2773//#testresult/52b59c23f61e0c15","status":"passed","time":{"start":1721180491048,"stop":1721181894847,"duration":1403799}},{"uid":"931d96f502ccd309","reportUrl":"../2769//#testresult/931d96f502ccd309","status":"passed","time":{"start":1721094261073,"stop":1721095657091,"duration":1396018}},{"uid":"bb3be3cb19a83c14","reportUrl":"../2764//#testresult/bb3be3cb19a83c14","status":"passed","time":{"start":1721007483780,"stop":1721009016720,"duration":1532940}},{"uid":"25aedbf51414085d","reportUrl":"../2763//#testresult/25aedbf51414085d","status":"passed","time":{"start":1720921236043,"stop":1720922625899,"duration":1389856}},{"uid":"81c2ecb62a7b9f0c","reportUrl":"../2762//#testresult/81c2ecb62a7b9f0c","status":"passed","time":{"start":1720834780348,"stop":1720836215750,"duration":1435402}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"a43b8720a154b270.json","parameterValues":[]}