[32mINFO    [0m pytest_operator.plugin:plugin.py:675 Connecting to existing model localhost-localhost:test on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:927 unexpected facade UserSecretsDrain received from the controller
[33mWARNING [0m juju.client.connection:connection.py:927 unexpected facade UserSecretsManager received from the controller
[32mINFO    [0m juju.model:model.py:2069 Deploying local:jammy/mysql-0
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [allocating] waiting: waiting for machine
  mysql/1 [allocating] waiting: waiting for machine
  mysql/2 [allocating] waiting: waiting for machine
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [allocating] waiting: agent initialising
  mysql/1 [allocating] waiting: agent initialising
  mysql/2 [allocating] waiting: agent initialising
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [executing] maintenance: Installing MySQL
  mysql/1 [executing] maintenance: Installing MySQL
  mysql/2 [executing] maintenance: Installing MySQL
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [executing] waiting: Waiting to join the cluster
  mysql/1 [executing] active: Primary
  mysql/2 [executing] maintenance: Setting up cluster node
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [executing] active: 
  mysql/1 [idle] active: Primary
  mysql/2 [executing] maintenance: Setting up cluster node
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/2 [executing] maintenance: Setting up cluster node
[32mINFO    [0m juju.model:model.py:2759 Waiting for model:
  mysql/0 [executing] active: 
  mysql/1 [executing] active: Primary
  mysql/2 [executing] maintenance: Setting up cluster node
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.3    unsupported  01:38:20Z

App    Version          Status  Scale  Charm  Channel  Rev  Exposed  Message
mysql  8.0.36-0ubun...  active      3  mysql             0  no       

Unit      Workload  Agent  Machine  Public address  Ports           Message
mysql/0   active    idle   0        10.155.230.86   3306,33060/tcp  
mysql/1*  active    idle   1        10.155.230.13   3306,33060/tcp  Primary
mysql/2   error     idle   2        10.155.230.54                   hook failed: "start"

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.155.230.86  juju-5f79a9-0  ubuntu@22.04      Running
1        started  10.155.230.13  juju-5f79a9-1  ubuntu@22.04      Running
2        started  10.155.230.54  juju-5f79a9-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

machine-1: 01:35:25 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:35:25 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:35:25 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:35:25 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:35:27 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:35:27 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:35:27 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-mysql-0: 01:35:27 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:35:28 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:35:28 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:35:28 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:35:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-2: 01:38:17 ERROR unit.mysql/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 362, in reset_root_password_and_start_mysqld
    self.wait_until_mysql_connection(check_port=False)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 375, in wait_until_mysql_connection
    raise MySQLServiceNotRunningError("MySQL socket file not found")
charms.mysql.v0.mysql.MySQLServiceNotRunningError: MySQL socket file not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/./src/charm.py", line 860, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-2/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/./src/charm.py", line 321, in _on_start
    self.workload_initialise()
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/./src/charm.py", line 657, in workload_initialise
    self._mysql.reset_root_password_and_start_mysqld()
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 544, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 364, in reset_root_password_and_start_mysqld
    raise MySQLResetRootPasswordAndStartMySQLDError("mysqld service not running")
mysql_vm_helpers.MySQLResetRootPasswordAndStartMySQLDError: mysqld service not running
unit-mysql-2: 01:38:17 ERROR juju.worker.uniter.operation hook "start" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...