[32mINFO    [0m integration.high_availability.test_upgrade_skip_pre_upgrade_check:test_upgrade_skip_pre_upgrade_check.py:63 Build charm locally
[32mINFO    [0m integration.high_availability.test_upgrade_skip_pre_upgrade_check:test_upgrade_skip_pre_upgrade_check.py:66 Refresh the charm
[32mINFO    [0m integration.high_availability.test_upgrade_skip_pre_upgrade_check:test_upgrade_skip_pre_upgrade_check.py:74 Wait for rolling restart OR continue to writes
[32mINFO    [0m integration.high_availability.test_upgrade_skip_pre_upgrade_check:test_upgrade_skip_pre_upgrade_check.py:88 Ensure continuous_writes
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:343 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:485 Retrieving primary unit
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:368 max_written_value=2779 on unit mysql/0
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:368 max_written_value=2780 on unit mysql/1
[32mINFO    [0m integration.high_availability.high_availability_helpers:high_availability_helpers.py:368 max_written_value=2782 on unit mysql/2
[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.5    unsupported  01:40:10Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.36-0ubun...  active      3  mysql                          0  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   63  no       

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   0        10.46.87.195                    
mysql/0            active    idle   1        10.46.87.165    3306,33060/tcp  
mysql/1            active    idle   2        10.46.87.3      3306,33060/tcp  
mysql/2*           active    idle   3        10.46.87.72     3306,33060/tcp  

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.46.87.195  juju-f60ed7-0  ubuntu@22.04      Running
1        started  10.46.87.165  juju-f60ed7-1  ubuntu@22.04      Running
2        started  10.46.87.3    juju-f60ed7-2  ubuntu@22.04      Running
3        started  10.46.87.72   juju-f60ed7-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

machine-0: 01:35:13 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:35:13 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:35:14 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:35:14 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:35:14 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-2: 01:35:14 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:35:18 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:35:18 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:35:18 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:35:20 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:35:20 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:35:20 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-1: 01:38:18 ERROR unit.mysql/1.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-2: 01:38:18 ERROR unit.mysql/2.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-0: 01:38:18 ERROR unit.mysql/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.
unit-mysql-1: 01:38:20 ERROR unit.mysql/1.juju-log Failed to get value for variable='super_read_only'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 717, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmpkzr_2sey']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/mysql/v0/mysql.py", line 1426, in get_variable_value
    output = self._run_mysqlsh_script("\n".join(get_var_command))
  File "/var/lib/juju/agents/unit-mysql-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-1/charm/src/mysql_vm_helpers.py", line 721, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError
unit-mysql-2: 01:38:20 ERROR unit.mysql/2.juju-log Failed to get value for variable='super_read_only'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 717, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmpmwf3rdgr']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/mysql/v0/mysql.py", line 1426, in get_variable_value
    output = self._run_mysqlsh_script("\n".join(get_var_command))
  File "/var/lib/juju/agents/unit-mysql-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-2/charm/src/mysql_vm_helpers.py", line 721, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError
unit-mysql-0: 01:38:20 ERROR unit.mysql/0.juju-log Failed to get value for variable='super_read_only'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 717, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmpnnywiubd']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 1426, in get_variable_value
    output = self._run_mysqlsh_script("\n".join(get_var_command))
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 721, in _run_mysqlsh_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError
unit-mysql-2: 01:38:20 ERROR unit.mysql/2.juju-log Failed to get cluster status for cluster-0aefab723e0ca922754b74d9d6e61385
unit-mysql-0: 01:38:49 ERROR unit.mysql/0.juju-log restart:2: Failed to get cluster status for cluster-0aefab723e0ca922754b74d9d6e61385
unit-mysql-1: 01:39:23 ERROR unit.mysql/1.juju-log restart:2: Failed to get cluster status for cluster-0aefab723e0ca922754b74d9d6e61385

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...