[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.7    unsupported  01:46:54Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.35-0ubun...  active      3  mysql                          0  no       
mysql-test-app  0.0.2            error       2  mysql-test-app  latest/edge   29  no       hook failed: "mysql-relation-changed"

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0   waiting   idle   0        10.45.133.242                   
mysql-test-app/1*  error     idle   1        10.45.133.194                   hook failed: "mysql-relation-changed"
mysql/0            active    idle   2        10.45.133.34    3306,33060/tcp  
mysql/1            active    idle   3        10.45.133.32    3306,33060/tcp  
mysql/2*           active    idle   4        10.45.133.21    3306,33060/tcp  Primary

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.45.133.242  juju-d97e1a-0  ubuntu@22.04      Running
1        started  10.45.133.194  juju-d97e1a-1  ubuntu@22.04      Running
2        started  10.45.133.34   juju-d97e1a-2  ubuntu@22.04      Running
3        started  10.45.133.32   juju-d97e1a-3  ubuntu@22.04      Running
4        started  10.45.133.21   juju-d97e1a-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:796 Juju error logs:

machine-1: 01:29:09 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:29:09 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:29:09 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-1: 01:29:09 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:29:15 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:29:15 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:29:15 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:29:16 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:29:29 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-4: 01:29:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:29:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-2: 01:29:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:29:31 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:29:31 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:29:31 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:29:31 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:29:32 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:29:32 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:29:32 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-1: 01:29:33 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-test-app-1: 01:31:59 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:32:00 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:32:05 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:32:05 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:32:16 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:32:16 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:32:37 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:32:37 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:33:19 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:33:19 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:34:40 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:34:40 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:37:24 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:37:25 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-mysql-test-app-1: 01:42:25 ERROR unit.mysql-test-app/1.juju-log mysql:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/./src/charm.py", line 409, in <module>
    main(MySQLTestApplication)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/src/relations/legacy_mysql.py", line 105, in _on_relation_changed
    self.charm.app_peer_data[f"{LEGACY_MYSQL_RELATION}-host"] = relation_data["host"]
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 1685, in __getitem__
    return super().__getitem__(key)
  File "/var/lib/juju/agents/unit-mysql-test-app-1/charm/venv/ops/model.py", line 790, in __getitem__
    return self._data[key]
KeyError: 'host'
unit-mysql-test-app-1: 01:42:25 ERROR juju.worker.uniter.operation hook "mysql-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Forgetting main...